import type { Metadata } from "next";
import { Barlow_Semi_Condensed, Nunito_Sans } from "next/font/google";
import "./globals.css";

const barlow = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["400","500","600","700"]
});

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400","500","600","700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nunito.className}
      >
        {children}
      </body>
    </html>
  );
}
